version: '3.8'

services:

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${POSTGRES_DATA}
    volumes:
       - postgres_volume:${POSTGRES_DATA}
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

  api:
    container_name: api
    hostname: api
    build:
      context: ./requirements/back-end
      dockerfile: Dockerfile
      target: production
    ports:
      - ${API_PORT}:${API_PORT}
      - ${PRISMA_PORT}:${PRISMA_PORT}
      - 3001:3001
    restart: unless-stopped
    networks:
      - db
      - back
    depends_on:
      - postgres
    environment:
      - MODE=production
      - DATABASE_URL=${DATABASE_URL}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - LOCAL_IP=${LOCAL_IP}
    command: ["npm", "run", "start:production"]

  front:
    container_name: front
    hostname: front
    build:
      context: ./requirements/front-end
      dockerfile: Dockerfile
      target: production
    ports:
      - ${FRONT_PORT}:${FRONT_PORT}
    environment:
      - API_PORT=${API_PORT}
      - PORT=${FRONT_PORT}
      - MODE=production
      - CLIENT_ID=${CLIENT_ID}
      - REACT_APP_LOCAL_IP=${LOCAL_IP}
    restart: unless-stopped
    networks:
      - back
    depends_on:
      - api
      - postgres
    command: ["serve", "-s", "build"]

networks:
  back:
    driver: bridge
  db:
    driver: bridge

volumes: 
  postgres_volume:

  