version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${POSTGRES_DATA}
    volumes:
       - postgres_volume:${POSTGRES_DATA}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - back
    restart: unless-stopped

  back-end:
    container_name: back-end
    hostname: back-end
    build:
      context: ./.dev/back-end
      dockerfile: Dockerfile
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    restart: unless-stopped
    networks:
      - back
    volumes:
      - back-end_volume:/var/www/back-end
    command: ["npm", "install", "/var/www/back-end", "&&", "sleep", "10000000"]

    # front:

networks:
  back:
    driver: bridge
  # front:
  #   driver: bridge

volumes: 
  postgres_volume:

  back-end_volume:
    driver: "local"
    driver_opts:
      type: "none"
      device: "./requirement/back-end"
      o: "bind"
  