version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${POSTGRES_DATA}
    volumes:
       - postgres_volume:${POSTGRES_DATA}
    expose:
      - "${POSTGRES_PORT}"
    networks:
      - db
    restart: unless-stopped

  back-end:
    container_name: back-end
    hostname: back-end
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
      - ${PRISMA_PORT}:${PRISMA_PORT}
    restart: unless-stopped
    networks:
      - db
    volumes:
      - ./../requirement/back-end:/home/back-end
    command: ["sleep", "100000000000"]

    # front:

networks:
  back:
    driver: bridge
  db:
    driver: bridge
  # front:
  #   driver: bridge

volumes: 
  postgres_volume:

  